### PR TITLE
Simple Bank management using C

### PR DESCRIPTION
**Pull request by sohampod**

### CODE REVIEW

**Comment by tb-rules10** [comment]
Good work

**Comment by sohampod** [comment]
@tb-rules10 can i make more PR into this same repo & will that be also counted towards Hacktoberfest?

**Comment by tb-rules10** [comment]
yes but not many else they will exclude my repo

**Comment by sohampod** [comment]
oh okay, cool.
i did 2 PR for the hacktoberfest and there's 2 left.
so should i do the remaining 2 PR at this repo or if you want i can add some python programs in some other hacktoberfest repo.
@tb-rules10

**Pull request merged**
